version: '3.8'

services:
  ai-mcp-toolkit:
    build: .
    ports:
      - "8000:8000"  # MCP Server
      - "5173:5173"  # Svelte UI
    environment:
      - OLLAMA_HOST=ollama
      - OLLAMA_PORT=11434
      - MCP_HOST=0.0.0.0
      - MCP_PORT=8000
      - LOG_LEVEL=INFO
    volumes:
      - ./data:/app/data
    depends_on:
      - ollama
    networks:
      - ai-mcp-network

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_ORIGINS=*
    networks:
      - ai-mcp-network
    # Uncomment for GPU support
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]

volumes:
  ollama_data:

networks:
  ai-mcp-network:
    driver: bridge
